### ISSUE TITLE
Some Commands aren't working

### ISSUE THREAD

**Issue by VoltDevelopment** [primitt/duino-stats-mini#2]
Commad:  +Balance

ERROR Can't fetch user data: Traceback (most recent call last):
  File "main.py", line 488, in on_message
    await message.channel.send(embed=embed)
  File "C:\Users\prian\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Users\prian\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.image.url: Scheme "none" is not supported. Scheme must be one of ('http', 'https').

**Comment by primitt** [comment]
Hello! This problem should be fixed! Sorry for not responding earlier.
